### ISSUE TITLE
feat(compile-commands): handle sources missing from the CDB

### ISSUE THREAD

**Issue by neko-para** [clice-io/clice#18]
After create a new source, it's fairly common that CDB is not updated instantly. In this case, clangd generally would use the default settings (and .clangd) to parse that file, which would run into trouble.

A possible solution is to fallback to sources near it. It is also possible to allow users explicitly specifying a fallback settings (not the same use case with .clangd).

---

Also, I'm wondering if clice would inherit the CDB format or design a new format. After all, CDB does have some shortcomings.

**Comment by 16bit-ykiko** [comment]
Yes, I have found this problem and plan to use the method you mentioned to solve it. As for the new CDB format, it requires the toolchain's support and might be challenging. Advancing this will take some time. For now, clice still use clang's CDB specification.

**Comment by Guo-Shiyu** [comment]
Currently, clice use `Synchronizer::lookup(llvm::StringRef file)` to find coresponding compile commands for a file, which will be called in 2 entries: `Scheduler::updateAST()`, `Scheduler::updatePCM()`.
``` cpp
// https://github.com/clice-project/clice/blob/5326480cd67efe6856cf2e450e15cd29d5fb5e7a/src/Server/Synchronizer.cpp
llvm::StringRef Synchronizer::lookup(llvm::StringRef file) const {
    auto iter = commands.find(file);
    if(iter == commands.end()) {
        return "";
    }
    return iter->second;
}
```

It seems that a new item `fallback_compile_commands` of string type needs to be added in configuration file `clice.toml`, the `server` section. And it has 2 case: `auto` or `<user defined commands>`. 

``` toml
[server]
    # Compile commands directories to search for compile_commands.json files.
    compile_commands_dirs = ["${workspace}/build"]

    # Fallback case for file not included in  compile_commands.json.
    # "auto" indicates clice to 'guess' the commands from other source file in the same directory,
    # while a costom string will be use as the commands directly.
    fallback_compile_commands = "auto"  # or user defined command like "-std=c++11 -I/path/to/include ..."
```

By the convenience of variable `extern const ServerOptions& server;` in `include/Server/Config.h`, refactoring the lookup function should be able to achieve the above goals.
